apiVersion: v1
kind: Secret
metadata:
  name: storage-gateway-secret
type: Opaque
stringData:
  MONGO_URI: mongodb://storage_gateway:storage_gateway_pw@storage-db:27017/storage_gateway?authSource=admin
