apiVersion: v1
kind: Secret
metadata:
  name: replication-planner-secret
type: Opaque
stringData:
  MONGO_URI: mongodb://replication_planner:replication_planner_pw@replication-db:27017/replication_planner?authSource=admin
